In [3]:
import numpy as np

def mysum(a):
    su = 0
    for i in a:
        su+=i
    return su
        

def mylength(a):
    le = 0
    for i in a:
        le+=1
    return le

def DET(x):
    s1  = x[1][1]*x[2][2] - x[2][1]*x[1][2] 
    s2 =  x[1][0]*x[2][2] - x[2][0]*x[1][2]
    s3 =  x[1][0]*x[2][1] - x[2][0]*x[1][1]
    res = x[0][0] * s1 - x[0][1] * s2 + x[0][2] * s3
    return res


x = np.array([float(x) for x in input("enter x values : ").split()])
y = np.array([ float(y) for y in input(" enter y values ").split()])
x2 = x*x
x3 = x2*x
x4 = x3*x
xy = x*y
x2y = x2*y

sx2 = mysum(x2)
sx3 = mysum(x3)
sx4 = mysum(x4)
sx2y = mysum(x2y)
sxy = mysum(xy)
sx = mysum(x)
sy = mysum(y)

n = mylength(x)

delta = DET([[n,sx,sx2],
            [sx,sx2,sx3],
            [sx2,sx3,sx4]])

delta1 = DET([[sy,sx,sx2],
            [sxy,sx2,sx3],
            [sx2y,sx3,sx4]])

delta2 = DET([[n,sy,sx2],
            [sx,sxy,sx3],
            [sx2,sx2y,sx4]])

delta3 = DET([[n,sx,sy],
            [sx,sx2,sxy],
            [sx2,sx3,sx2y]])


a  = delta1 / delta
b  = delta2 / delta
c  = delta3 / delta 

print(" the calculated parabola  y=",a,"+",b,"x+",c,"x^2 is the best fit . ")

enter x values : 5 6 7 8 


KeyboardInterrupt: Interrupted by user

In [20]:


def mymean(x):
    su = mysum(x)
    return su/mylength(x)

def mysd(x):
    su = 0
    xbar = mymean(x)
    n = mylength(x)
    for i in x :
        su  = su + (np.square(i-xbar))/n
    return np.sqrt(su)

def cov(x,y):
    xbar = mymean(x)
    ybar = mymean(y)
    n = mylength(x)
    su = 0
    for i in range(0,n):
        su = su + x[i]*y[i]
    su = su / n
    return  ( su -( xbar*ybar ))

def corr_coeff(x,y):
    return  ( cov(x,y) / (mysd(x)*mysd(y)) )
        
    
x = np.array([float(x) for x in input("enter x values : ").split()])
y = np.array([ float(y) for y in input(" enter y values ").split()])


print(" correlation coefficient r = ",corr_coeff(x,y))

print(mymean(x))
print(mysd(x))
print(cov(x,y))



KeyboardInterrupt: Interrupted by user

In [36]:
#x = np.array([float(x) for x in input("enter x values : ").split()])
#y = np.array([ float(y) for y in input(" enter y values ").split()])

def co_coeff(x,y):
    d = np.array(x-y) 
    d2 = d*d
    sd2 = mysum(d2)
    rx = list()
    ry = list()
    x1 = np.copy(x)
    y1 = np.copy(y)
    n = length(x1)
    for i in range(n):
         v= max(x1)
         r
    
    dup = list()
    for i in x:
        ct = 0
        for j in x:
            if  ( i==j ):
                ct = ct + 1
        if (ct > 1):
            dup.append(ct)
    for i in y:
        ct = 0
        for j in y:
            if  ( i==j ):
                ct = ct + 1
        if (ct > 1):
            dup.append(ct)
    dup = np.array(dup)
    var = 0
    for i in dup:
        var =  var + ( (i*(np.square(i)-1)) / 12)
    sd2 = sd2 + var
    print(sd2)
    res =  ( 6*sd2 ) / (n*(np.square(n)-1))
    return 1-res

print(" the  spearman correlation coefficient : ",co_coeff(x,y))

x = np.array([115,109,112,87,98,120,98,100,98,118])
y = np.array([75,73,85,70,76,82,65,73,68,80])



10011.0
 the  spearman correlation coefficient :  -499.55


In [ ]:

import scipy.stats as ss

def sq_sum(x):
    su = 0
    for i in x :
        su = su + np.square(i)
    return su

x = np.array([float(x) for x in input("enter x values : ").split()])
y = np.array([ float(y) for y in input(" enter y values ").split()])
z = np.array([float(x) for x in input("enter x values : ").split()])

alpha = float(input("enter alpha value : "))

sx = mysum(x)
sy = mysum(y)
sz = mysum(z)

g = sx+sy+sz

st2_by_n = (sx*sx)/mylength(x) + sy*sy/mylength(y) +sz*sz/mylength(z)

rss = 0 
for i in x:
    rss = rss + i*i
for i in y:
    rss = rss + i*i
for i in z:
    rss = rss + i*i
    
print("rss= ",rss)

N = mylength(x)+mylength(y)+mylength(z)
cf = g*g / N

print(st2_by_n)
print("correction factor = ",cf)
sst = rss - cf 
print("SST = ",sst)

sstr = st2_by_n - cf

print("SSTR =  ",sstr)

sse = sst - sstr

print("SSE = ",sse)

k = 3

msstr = sstr / (k-1)
msse = sse / (N-k)

fcal = msstr / msse
print("calculated  value ",fcal)
FTable = ss.f.ppf(1-alpha, k-1, N-k)
print(" FTable-Value :  ",FTable)

if(FTable >= fcal):
    print(" fcal <= ftable_value , we accept ho .")
else :
    print(" fcal > ftable_value , we reject ho  .")

In [7]:
k = int(input("Enter the number of Treatments: "))
h = int(input("Enter the number of Blocks: "))
# k = 4
# h = 5

Treatment = input("Enter name of the Treatments: ")
Block = input("Enter name of the Blocks: ")
# Treatment = "Form"
# Block = "Student"

Data = []
for i in range(k):
    row = []
    while mylen(row) != h:
        row = np.array([float(i) for i in input(f"Enter {Treatment} {i+1} values: ").strip().split()])
    Data.append(row)
                       
Data = np.array(Data)

# Data = np.array([[75,73,59,69,84],[83,72,56,70,92],[86,61,53,72,88],[73,67,62,79,95]])

alpha = float(input("Enter Level of Significance: "))
# alpha = 0.05

# Total no. of values:
N = k * h

Ti = [mysum(i) for i in Data]
Ti2 = np.square(Ti)
SumTi2 = mysum(Ti2)

Bj = Data[0]
for i in range(1,k):
    Bj = np.add(Bj,Data[i])
    
Bj2 = np.square(Bj)
SumBj2 = mysum(Bj2)

# Grand Total:
G = mysum(Ti) # G = mysum(Bj)
# Row Sum of Squares:
RSS = 0

for i in Data:
    for j in i:
        RSS += j**2
# Correction Factor:
CF = G**2 / N

# Sum of Squares due to Total:
SST = RSS - CF
# Sum of Squares due to Treatments:
SSTr = SumTi2/h - CF
# Sum of Squares due to Blocks:
SSB = SumBj2/k - CF
# Sum of Squares due to Error:
SSE = SST - SSTr - SSB

# Mean Sum of Squares due to Treatments:
MeanSSTr = SSTr/(k-1)
# Mean Sum of Squares due to Blocks:
MeanSSB = SSB/(h-1)
# Mean Sum of Squares due to Error:
MeanSSE = SSE/((k-1)*(h-1))

# F calculated value of Treatments:
F_Tr_cal = MeanSSTr / MeanSSE
# F calculated value of Blocks:
F_B_cal = MeanSSB / MeanSSE

if(F_Tr_cal < 1):
    F_Tr_cal = 1 / F_Tr_cal

if(F_B_cal < 1):
    F_B_cal = 1 / F_B_cal

# F table value of Treatments:
F_Tr_Table = ss.f.ppf(1-alpha, k-1, (k-1)*(h-1))
# F table value of Blocks:
F_B_Table = ss.f.ppf(1-alpha, h-1, (k-1)*(h-1))

print("\nTi values: ",Ti)
print("Ti2 values: ",Ti2)
print("Sum of Ti2: ",SumTi2)

print("\nBj values: ",Bj)
print("Bj2 values: ",Bj2)
print("Sum of Bj2: ",SumBj2)

print("\nGrand Total (G): ",G)
print("Row Sum of Squares (RSS): ",RSS)
print("Correction Factor (CF): {:.4f}".format(CF))

print("\nSum of Squares due to Total (SST): {:.4f}".format(SST))
print("Sum of Squares due to Treatments (SSTr): {:.4f}".format(SSTr))
print("Sum of Squares due to Blocks (SSB): {:.4f}".format(SSB))
print("Sum of Squares due to Error (SSE): {:.4f}".format(SSE))

print("\nMean Sum of Squares due to Treatments (Mean SSTr): {:.4f}".format(MeanSSTr))
print("Mean Sum of Squares due to Blocks (Mean SSB): {:.4f}".format(MeanSSB))
print("Mean Sum of Squares due to Error (Mean SSE): {:.4f}\n".format(MeanSSE))

ANOVA_Two_Way_Classification_Table = {
    "S O V": [Treatment+'s', Block+'s', "Error", "Total"],
    "S O S": ["{:.4f}".format(SSTr), "{:.4f}".format(SSB), "{:.4f}".format(SSE), "{:.4f}".format(SST)],
    "D O F": [k-1, h-1, (k-1)*(h-1), (k*h)-1],
    "M S O S": ["{:.4f}".format(MeanSSTr), "{:.4f}".format(MeanSSB), "{:.4f}".format(MeanSSE), " - "],
    "V R": ["F(Tr)-cal = {:.4f}".format(F_Tr_cal), "~ F(k-1, (k-1)(h-1))", "F(B)-cal = {:.4f}".format(F_B_cal),"~ F(h-1, (k-1)(h-1))"]
}

data_frame = pd.DataFrame(ANOVA_Two_Way_Classification_Table)

print(data_frame) 

print(f"\nInference Related to {Treatment}s:")
print("F(Tr)-Calculated Value: {:.4f}".format(F_Tr_cal))
print("F(Tr)-Table Value: {:.4f}".format(F_Tr_Table))

if(F_Tr_cal < F_Tr_Table):
    print(f"We Accept H0(Tr)\nThere is Homogeneity among the {Treatment}s")
else:
    print(f"We Reject H0(Tr)\nThere is Heterogeneity among the {Treatment}s")
    
print(f"\nInference Related to {Block}s:")
print("F(B)-Calculated Value: {:.4f}".format(F_B_cal))
print("F(B)-Table Value: {:.4f}".format(F_B_Table))

if(F_B_cal < F_B_Table):
    print(f"We Accept H0(B)\nThere is Homogeneity among the {Block}s")
else:
    print(f"We Reject H0(B)\nThere is Heterogeneity among the {Block}s")

Enter the number of Treatments: 4
Enter the number of Blocks: 5
Enter name of the Treatments: a b c d
Enter name of the Blocks: s1 s2 s3 s4 s5


NameError: name 'mylen' is not defined

In [15]:
h=  int(input("enter no of bloks:  "))
k= int(input(" enter no of treatments : "))

treatment = input("enter name  of treatment : ")
block  = input(" enter name of blocks  :  ")

data =[]

for i in range(k) :
    row=[]
    while mylength(row)!= h:
        row= np.array([float(x) for x in input(f"enter {treatment} {i+1}   values : ").strip().split()])
       
    data.append(row)

data = np.array(data)

print(" data : ",data)

ti = [mysum(i) for i in data]
ti2 = np.square(ti) 
sti2 = mysum(ti2)

bj = data[0]
for i in range(1,k):
    bj  = np.add(bj,data[i])

bj2 = bj*bj
sbj2 = mysum(bj2)

g = mysum(ti)

rss = 0
for i in data:
    rss = rss + i*i
print(" RSS = ",rss

cf = ( g*g) / (k*h
print(" CF = ",cf)

sst = rss-cf
print("SST = ",sst)

sstr = ((1/h)*sti2) - cf
print("SSTR = ",sstr)

ssb = ((1/k)*sti2) - cf
print("SSB = ",ssb)

sse = sst - sstr - ssb
print("SSE = ",sse)




enter no of bloks:  5
 enter no of treatments : 4
enter name  of treatment : form
 enter name of blocks  :  student
enter form 1   values : 75 73 59 69 84
enter form 2   values : 83 72 56 70 92
enter form 3   values : 86 61 53 72 88
enter form 4   values : 73 67 62 79 95
 data :  [[75. 73. 59. 69. 84.]
 [83. 72. 56. 70. 92.]
 [86. 61. 53. 72. 88.]
 [73. 67. 62. 79. 95.]]
 RSS =  [25239. 18723. 13270. 21086. 32289.]


NameError: name 't' is not defined

In [19]:
a = [25239, 18723, 13270, 21086, 32289]
print(np.sum(a))

110607


In [ ]:
import numpy as np
from math import sqrt
import numpy.linalg as m

def muliply(a,b):
    if a.shape[0] != b.shape[1] :
        print(" the multiplicatio is not possible ")
        return None
    c = np.zeros([a.shape[0],b.shape[1]],dtype=float)
    for i in range len((a)):
        for j in range((b[0])):
            for k in range(len(b)):
                c[i,j] += a[i,k] * b[k,j]
    return c

def transpose(mat):
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            mat[i,j] = mat[j,i]
    return mat

def recursivedet(mat):
    if mat.shape() = (2,2):
        return mat[1,1]*mat[2,2] - mat[1,2]*mat[2,1]
    res = 0                                                                             
    return m.det(mat)

def myInv(mat):
    det = recursiveDet(mat)
    adj = np.zeros(mat.shape, dtype=float)
    for r in range(mat.shape[0]):
        matC = np.copy(mat)
        matC = np.delete(matC, r, 0)
        for c in range(matC.shape[1]):
            matC2 = np.delete(matC, c, 1)
            adj[r, c] = ((-1)**(c%2)) * recursiveDet(matC2)
    adj = adj/det
    return adj

#p1 = int(input(" enter  y values : "))
#p2= int(input("entre x values : "))
#n = int(input(" entre no of observatins  : "))

 y = np.array([[10, 100], [12, 110], [11, 105], [9, 94], [9, 95], [10, 99], [11, 104], [12, 108], [11, 105], [10, 98], [11, 103], [12, 110]])
 x = np.array([[1, 9, 62, 1.0], [1, 8, 58, 1.3], [1, 7, 64, 1.2], [1, 14, 60, 0.8], [1, 12, 63, 0.8], [1, 10, 57, 0.9], [1, 7, 55, 1.0], [1, 4, 56, 1.2
    
    
            
            
    
    
    
    
    
    
    
    

9. 9.	Write a python program to classify the treatments based on MANOVA Test.

In [30]:
t1 = np.array([[9,3],[6,2],[9,7]])
t2 = np.array([[0,4],[2,0]])
t3 = np.array([[3,8],[1,9],[2,7]])

def yib(t1):
    s1 = 0
    s2 = 0
    for i in range(t1.shape[0]):
        s1 = s1+t1[i,0]
        s2 = s2+t1[i,1]
    s1 ,s2 = s1/len(t1),s2/len(t1)
    return list([s1,s2])

def val(){
    s1 = np.array()
    s2 = np.array()
    for i in range(t1.shape[0]):
        s1 = s1.append(t1[i,0])
        s2 = s2.append(t1[i,1])
    for i in range(t2.shape[0]):
        s1 = s1.append(t2[i,0])
        s2 = s2.append(t2[i,1])
    for i in range(t3.shape[0]):
        s1 = s1.append(t3[i,0])
        s2 = s2.append(t3[i,1])
    return list([s1,s2])
}

yibar = np.array(list([yib(t1),yib(t2),yib(t3)]))

def ydb():
    s1 = 0
    s2 = 0
    for i in range(t1.shape[0]):
        s1 = s1+t1[i,0]
        s2 = s2+t1[i,1]
    for i in range(t2.shape[0]):
        s1 = s1+t2[i,0]
        s2 = s2+t2[i,1]
    for i in range(t3.shape[0]):
        s1 = s1+t3[i,0]
        s2 = s2+t3[i,1]
    n = len(t1)+len(t2)+len(t3)
    s1,s2=s1/n,s2/n
    
    ydbar = list([s1,s2])
    return ydbar

ydbar = ydb()
print(ydbar)

#for Y1 :
sst = 0
for i in ss1 :
    sst = sst+np.square(i-ydbr[0])
sse = 0
for i in range(t1.shape[]
    
    





        
        

[4.0, 5.0]
